{{- if (not .Values.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mariadb-galera.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mariadb-galera.name" . }}
    helm.sh/chart: {{ include "mariadb-galera.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.rootUser.password }}
  mariadb-root-password: {{ .Values.rootUser.password | b64enc | quote }}
  {{- else if (not .Values.rootUser.forcePassword) }}
  mariadb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  mariadb-root-password: {{ required "A MariaDB Root Password is required!" .Values.rootUser.password }}
  {{- end }}
  {{- if .Values.db.user }}
  {{- if .Values.db.password }}
  mariadb-password: {{ .Values.db.password | b64enc | quote }}
  {{- else if (not .Values.db.forcePassword) }}
  mariadb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- else }}
  mariadb-password: {{ required "A MariaDB Database Password is required!" .Values.db.password }}
  {{- end }}
  {{- end }}
  {{- if .Values.galera.mariabackup.password }}
  mariadb-galera-mariabackup-password: {{ .Values.galera.mariabackup.password | b64enc | quote }}
  {{- else if (not .Values.galera.mariabackup.forcePassword) }}
  mariadb-galera-mariabackup-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{ else }}
  mariadb-galera-mariabackup-password: {{ required "A MariaBackup Password is required!" .Values.galera.mariabackup.password }}
  {{- end }}
  {{- if .Values.ldap.enabled }}
  {{- if .Values.ldap.bindpw }}
  ldap-bindpw: {{ .Values.ldap.bindpw | b64enc | quote }}
  {{ else }}
  ldap-bindpw: {{ required "LDAP Password is required!" .Values.ldap.bindpw }}
  {{- end }}
  {{- end }}
{{- end }}
